#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/data1/baibing/espnet3/tools/python_user_base"
export PATH="/data1/baibing/espnet3/tools/python_user_base/bin":${PATH}
export PATH=/data1/baibing/miniconda3/envs/espnet/bin:${PATH}
